exports.config = {
	CLEAN_ON_STARTUP: true,
	DEBUG: true,
	PORT: 3022,
	BLACKLIST: [],
	SECTION_BANS_NAME: "Bye Felicias",
	SECTION_BITS_NAME: "Thanks for the Bits!",
	SECTION_CHANNELPOINTS_NAME: "Special Interactions Provided By",
	SECTION_CHATTERS_NAME: "The Voices In My Head",
	SECTION_DONOS_NAME: "Todays Donations",
	SECTION_FOLLOWS_NAME: "Todays Follows",
	SECTION_GIFTSUBS_NAME: "Many Thanks For The Gift Subs",
	SECTION_HOSTS_NAME: "Todays Stream Was Hosted By",
	SECTION_MODS_NAME: "Todays Moderators",
	SECTION_PATREONS_NAME: "New Patrons",
	SECTION_RAIDS_NAME: "The Raids",
	SECTION_STREAMLOOTS_NAME: "StreamLoots Interactions",
	SECTION_SUBS_NAME: "New and Renewing Subs",
	SECTION_VIPS_NAME: "Todays VIPs",
	SECTION_BITS_NAME_AMOUNT: "Bits and Who Spent Them",
	SECTION_CHANNELPOINTS_NAME_AMOUNT: "Channel Points and Who Spent Them",
	SECTION_CHATTERS_NAME_AMOUNT: "Stream Chat Details",
	SECTION_DONOS_NAME_AMOUNT: "Donation Details",
	SECTION_GIFTSUBS_NAME_AMOUNT: "Gifted Subs Today",
	SECTION_STREAMLOOTS_NAME_AMOUNT: "StreamLoots Cards Played By Viewer",
	SECTION_BITS_NAME_TOTAL: "Total Bits Spent By Viewers",
	SECTION_CHANNELPOINTS_NAME_TOTAL: "Total Channel Points Spent By Viewers",
	SECTION_DONOS_NAME_TOTAL: "Total Donations From Viewers",
	SECTION_GIFTSUBS_NAME_TOTAL: "Total Subs Gifted By Viewers",
	SECTION_HOSTS_NAME_TOTAL: "Total Hosts By Viewers",
	SECTION_RAIDS_NAME_TOTAL: "Total Raids By Viewers",
	SECTION_STREAMLOOTS_NAME_TOTAL: "Total Cards By Viewers",
	SECTION_SUBS_NAME_TOTAL: "Total Subs By Viewers",
	SECTION_BITS_NAME_AMOUNT_TOTAL: "Bits: Today and Total By Viewers",
	SECTION_CHANNELPOINTS_NAME_AMOUNT_TOTAL: "Channel Points Today and Total By Viewers",
	SECTION_DONOS_NAME_AMOUNT_TOTAL: "Donations Today and Total By Viewers",
	SECTION_GIFTSUBS_NAME_AMOUNT_TOTAL: "Gifted Subs Today and Total By Viewers",
	SECTION_STREAMLOOTS_NAME_AMOUNT_TOTAL: "StreamLoots cards Today and Total by Viewers",
	SECTION_BITS_TOP10: "Top 10 Bits Today",
	SECTION_CHANNELPOINTS_TOP10: "Top 10 Channel Points Today",
	SECTION_CHATTERS_TOP10: "Top 10 Chatty People Today",
	SECTION_DONOS_TOP10: "Top 10 Donos Today",
	SECTION_GIFTSUBS_TOP10: "Top 10 Sub Gifters Today",
	SECTION_STREAMLOOTS_TOP10: "Top 10 StreamLoots Users",
	SECTION_BITS_TOP5: "Top 5 Bits Today",
	SECTION_CHANNELPOINTS_TOP5: "Top 5 Channel Points Today",
	SECTION_CHATTERS_TOP5: "Top 5 Chatty People Today",
	SECTION_DONOS_TOP5: "Top 5 Donations Today",
	SECTION_GIFTSUBS_TOP5: "Top 5 Sub Gifters Today",
	SECTION_STREAMLOOTS_TOP5: "Top 5 StreamLoots Users",
	SECTION_HBITS_TOP10H: "Overall Top 10 Bits",
	SECTION_HCHANNELPOINTS_TOP10H: "Overall Top 10 Channel Points",
	SECTION_HDONOS_TOP10H: "Overall Top 10 Donations",
	SECTION_HGIFTSUBS_TOP10H: "Overall Top 10 Sub Gifters",
	SECTION_HHOSTS_TOP10H: "Overall Top 10 Hosts",
	SECTION_HRAIDS_TOP10H: "Overall Top 10 Raiders",
	SECTION_HSTREAMLOOTS_TOP10H: "Overall Top 10 StreamLoots Users",
	SECTION_HSUBS_TOP10H: "Overall Top 10 Subscribers",
	SECTION_HBITS_TOP5H: "Overall Top 5 Bits",
	SECTION_HCHANNELPOINTS_TOP5H: "Overall Top 5 Channel Points",
	SECTION_HDONOS_TOP5H: "Overall Top 5 Donations",
	SECTION_HGIFTSUBS_TOP5H: "Overall Top 5 Sub Gifters",
	SECTION_HHOSTS_TOP5H: "Overall Top 5 Hosts",
	SECTION_HRAIDS_TOP5H: "Overall Top 5 Raiders",
	SECTION_HSTREAMLOOTS_TOP5H: "Overall Top 5 StreamLoots Users",
	SECTION_HSUBS_TOP5H: "overall Top 5 Subscribers",
	SECTION_STREAMLOOTS_TOP5_CARDS: "Top 5 StreamLoots Cards",
	SECTION_STREAMLOOTS_TOP10_CARDS: "Top 10 StreamLoots Cards",
	SECTION_HSTREAMLOOTS_TOP5H_CARDS: "Overall Top 5 StreamLoots Cards",
	SECTION_HSTREAMLOOTS_TOP10H_CARDS: "Overall Top 10 StreamLoots Cards",
};